FRONT: [UPDT] updated all committee members info! so far
UCLAIS/UCLAIS.github.io pull request #8
Opened 2023-09-26 16:29 UTC by wonjunlee33

Updated all committee members info! I have left the Tutorials Team untouched, and all missing sub info has been left blank.

2023-09-26 22:16 UTC, Willmish commented
Cool, can you confirm it builds for you locally? A screenshot would be nice :) 

Otherwise I'll build it up tomorrow and give it a review

2023-09-26 22:56 UTC, wonjunlee33 commented
Szy

> Cool, can you confirm it builds for you locally? A screenshot would be nice :)
> 
> Otherwise I'll build it up tomorrow and give it a review

@Willmish , can confirm it builds locally! 

<img width="1470" alt="Screenshot 2023-09-26 at 23 53 42" src="https://github.com/UCLAIS/UCLAIS.github.io/assets/67159793/1a755bad-9a77-4151-a5aa-3b13c27b684a">

2023-09-27 00:48 UTC, TheRootOf3 requested changes
Please have a look at the comments. 
Mainly remove the `languages` field completely, and add periods at the end of sentences! Well done! 🎉

2023-09-27 00:48 UTC, TheRootOf3 commented on src/data/committee.js
>            languages: 'English... kidding a bit of Python',
I think we want to get rid of `languages` completely, so please remove them wherever someone specified them previously. We will just stick with `ai_concept`.

2023-09-27 00:48 UTC, TheRootOf3 commented on src/data/committee.js
> +          fact: 'I can cook minute rice in 58 seconds.',
Love it! hahahha 🤣

2023-09-27 00:48 UTC, TheRootOf3 commented on src/data/committee.js
> +          fact: 'I became a competitive fencer after I was kicked out from music school',
nit: please add period at the end of the sentence for consistency.

2023-09-27 00:48 UTC, TheRootOf3 commented on src/data/committee.js
> +          fact: 'I spent 4 months living at a Buddhist temple ',
nit: Same here. Period at the end.

2023-09-27 00:48 UTC, TheRootOf3 commented on src/data/committee.js
> +          fact: 'I write poetry in French and am creating a book',
nit: Period at the end here as well!

2023-09-27 14:03 UTC, wonjunlee33 commented
@TheRootOf3 , rmved languages section, added consistency. please check!

<img width="1459" alt="Screenshot 2023-09-27 at 15 02 08" src="https://github.com/UCLAIS/UCLAIS.github.io/assets/67159793/87f61625-c20c-477a-bbe5-fa38d03d5ec6">

2023-09-27 14:49 UTC, TheRootOf3 approved these changes
LGTM, well done! 🎉 
I suggest you squash these commits and merge - this will result in a single commit and keep our tree cleaner!

2023-09-27 14:51 UTC, TheRootOf3 requested changes
Sorry, one last thing!

2023-09-27 14:51 UTC, TheRootOf3 commented on src/pages/about-us.js
> +                        )} */}
Please remove completely if unused!

2023-09-27 17:30 UTC, wonjunlee33 commented
@TheRootOf3 , rmved unnecessary code.

2023-09-27 19:39 UTC, Willmish requested changes
Heyo - some changes necessary (remove HEIC file not used anywhere, see comments above), and some optional ones - pending @TheRootOf3 confirmation (might just be being picky, but IMO no need to have such large files, if they get downscaled to super small ones on the client side!)

2023-09-27 19:39 UTC, Willmish commented on static/img/committee/arham_ali.HEIC
Can we remove this file? looks like its not being used anywhere.

2023-09-27 19:39 UTC, Willmish commented on static/img/committee/charlie_harrison.PNG
suggest we convert to jpg to reduce file size/rescale the png?, (7.7MB vs few KB - 1 MB). but thats up to you, will probably render fine, but bloat up the page (and we already downscale the images on deployed website!)

2023-09-27 19:39 UTC, Willmish commented on src/data/committee.js
> +          image: 'charlie_harrison.PNG',
Make sure to change this path, if you end up converting png to jpg

2023-09-27 19:39 UTC, Willmish commented on static/img/committee/franek_nowak.jpg
this is a huge file, probably can lower quality/rescale - let me know your thoughts @TheRootOf3 as well (dont want to be too picky :P)

2023-09-27 23:05 UTC, TheRootOf3 commented on static/img/committee/arham_ali.HEIC
Yeah, for this one please do, nice catch btw! 
I'll create a separate issue to clean/downscale other images, since we will be adding more of them soon.

2023-09-27 23:07 UTC, TheRootOf3 commented on static/img/committee/charlie_harrison.PNG
These are very good points. However, I suggest we push this one without converting, and once we have another batch of peoples metadata + pictures, we will resize/convert them. I created a separate issue for that: #9

2023-09-27 23:07 UTC, TheRootOf3 commented on static/img/committee/franek_nowak.jpg
These are very good points. However, I suggest we push this one without converting, and once we have another batch of peoples metadata + pictures, we will resize/convert them. I created a separate issue for that: #9

2023-09-27 23:27 UTC, wonjunlee33 commented
removed HEIC file. i think we can move to issue 9 now?

2023-09-27 23:34 UTC, TheRootOf3 approved these changes
LGTM, well done! 🎉
I suggest you squash these commits and merge - this will result in a single commit and keep our tree cleaner!
In the next PR, where we will update/add more people, I suggest we can also solve #9.

2023-09-28 07:07 UTC, Willmish commented on static/img/committee/charlie_harrison.PNG
Sounds good! Agreed, lets get this one out first

2023-09-28 07:10 UTC, Willmish approved these changes
LGTM! as discussed - rescaling will be handled in next PR (#9)

Agreed with @TheRootOf3 , let's squash this as we have a bunch of small commits

2023-09-28 07:13 UTC, merged